name: 'notion-pr-link'
description: 'Update Notion task with GitHub PR'
author: 'kadaradam'
inputs:
  pr_body:
    required: true
    description: 'The body of your pull request'
    default: '.'
runs:
  using: 'node16'
  main: 'dist/index.js'
