name: 'notion-pr-link'
description: 'Update Notion task with GitHub PR'
author: 'kadaradam'
inputs:
  notion_secret:
    required: true
    description: 'The secret for Notion API'
    default: '.'
  pr_body:
    required: false
    description: 'Notion property to update with GitHub PR value'
    default: 'PR'
runs:
  using: 'node16'
  main: 'dist/index.js'
