name: 'notion-pr-link'
description: 'Update Notion task with GitHub PR'
author: 'kadaradam'
inputs:
  notion_secret:
    required: true
    description: 'The secret for Notion API'
    default: '.'
  notion_prop:
    required: false
    description: 'The Notion page property to update'
    default: 'PR'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'link'  
  color: 'red'
